<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Styles\Components
 * @copyright   Copyright (c) 2024, WeCodeArt Framework
 * @since		6.2.9
 * @version		6.3.7
 */

namespace WeCodeArt\Support\Modules\Formatting\Styles;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Support\Styles\Components\Base;

/**
 * Module Styles
 */
class Tooltip extends Base {
    /**
     * Component's Style Deps.
     *
     * @var     array
     */
    static $deps = [ 'transition' ];

    /**
	 * Component styles.
	 *
	 * @return 	string
	 */
	public static function styles(): string {
        return <<<CSS
            .wp-tooltip {
                --wp--tooltip--zindex: 80;
                --wp--tooltip--max-width: 200px;
                --wp--tooltip--padding-x: 0.5rem;
                --wp--tooltip--padding-y: 0.25rem;
                --wp--tooltip--margin: ;
                --wp--tooltip--font-size: var(--wp--preset--font-size--small);
                --wp--tooltip--color: var(--wp--preset--color--white);
                --wp--tooltip--border-radius: 3px;
                --wp--tooltip--bg: var(--wp--preset--color--dark);
                --wp--tooltip--opacity: 0.9;
                --wp--tooltip--arrow-width: 0.8rem;
                --wp--tooltip--arrow-height: 0.4rem;
                z-index: var(--wp--tooltip--zindex);
                display: block;
                margin: var(--wp--tooltip--margin);
                font-family: var(--wp--preset--font-family--base);
                font-size: var(--wp--tooltip--font-size);
                font-style: normal;
                font-weight: 400;
                text-align: left;
                text-align: start;
                text-decoration: none;
                text-shadow: none;
                text-transform: none;
                letter-spacing: normal;
                line-height: 1.5;
                line-break: auto;
                word-break: normal;
                white-space: normal;
                word-spacing: normal;
                word-wrap: break-word;
                opacity: 0;
            }
            .wp-tooltip.show {
                opacity: var(--wp--tooltip--opacity);
            }
            .wp-tooltip__arrow {
                position: absolute;
                display: block;
                width: var(--wp--tooltip--arrow-width);
                height: var(--wp--tooltip--arrow-height);
            }
            .wp-tooltip__arrow::before {
                position: absolute;
                content: '';
                border-color: transparent;
                border-style: solid;
            }
            
            .wp-tooltip--top .wp-tooltip__arrow,
            .wp-tooltip--auto[data-placement^=top] .wp-tooltip__arrow {
                bottom: calc(-1 * var(--wp--tooltip--arrow-height));
            }
            .wp-tooltip--top .wp-tooltip__arrow::before,
            .wp-tooltip--auto[data-placement^=top] .wp-tooltip__arrow::before {
                top: -1px;
                border-width: var(--wp--tooltip--arrow-height) calc(var(--wp--tooltip--arrow-width) * 0.5) 0;
                border-top-color: var(--wp--tooltip--bg);
            }
            
            /* rtl:begin:ignore */
            .wp-tooltip--end .wp-tooltip__arrow,
            .wp-tooltip--auto[data-placement^=right] .wp-tooltip__arrow {
                left: calc(-1 * var(--wp--tooltip--arrow-height));
                width: var(--wp--tooltip--arrow-height);
                height: var(--wp--tooltip--arrow-width);
            }
            .wp-tooltip--end .wp-tooltip__arrow::before,
            .wp-tooltip--auto[data-placement^=right] .wp-tooltip__arrow::before {
                right: -1px;
                border-width: calc(var(--wp--tooltip--arrow-width) * 0.5) var(--wp--tooltip--arrow-height) calc(var(--wp--tooltip--arrow-width) * 0.5) 0;
                border-right-color: var(--wp--tooltip--bg);
            }
            
            /* rtl:end:ignore */
            .wp-tooltip--bottom .wp-tooltip__arrow,
            .wp-tooltip--auto[data-placement^=bottom] .wp-tooltip__arrow {
                top: calc(-1 * var(--wp--tooltip--arrow-height));
            }
            .wp-tooltip--bottom .wp-tooltip__arrow::before,
            .wp-tooltip--auto[data-placement^=bottom] .wp-tooltip__arrow::before {
                bottom: -1px;
                border-width: 0 calc(var(--wp--tooltip--arrow-width) * 0.5) var(--wp--tooltip--arrow-height);
                border-bottom-color: var(--wp--tooltip--bg);
            }
            
            /* rtl:begin:ignore */
            .wp-tooltip--start .wp-tooltip__arrow,
            .wp-tooltip--auto[data-placement^=left] .wp-tooltip__arrow {
                right: calc(-1 * var(--wp--tooltip--arrow-height));
                width: var(--wp--tooltip--arrow-height);
                height: var(--wp--tooltip--arrow-width);
            }
            .wp-tooltip--start .wp-tooltip__arrow::before,
            .wp-tooltip--auto[data-placement^=left] .wp-tooltip__arrow::before {
                left: -1px;
                border-width: calc(var(--wp--tooltip--arrow-width) * 0.5) 0 calc(var(--wp--tooltip--arrow-width) * 0.5) var(--wp--tooltip--arrow-height);
                border-left-color: var(--wp--tooltip--bg);
            }
            
            /* rtl:end:ignore */
            .wp-tooltip__inner {
                max-width: var(--wp--tooltip--max-width);
                padding: var(--wp--tooltip--padding-y) var(--wp--tooltip--padding-x);
                color: var(--wp--tooltip--color);
                text-align: center;
                background-color: var(--wp--tooltip--bg);
                border-radius: var(--wp--tooltip--border-radius);
            }
        CSS;
	}
}