<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Styles\Components
 * @copyright   Copyright (c) 2024, WeCodeArt Framework
 * @since		6.3.7
 * @version		6.3.7
 */

namespace WeCodeArt\Support\Modules\Formatting\Styles;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Support\Styles\Components\Base;

/**
 * Module Styles
 */
class Floating extends Base {
    /**
     * Component's Style Deps.
     *
     * @var     array
     */
    static $deps = [ 'transition' ];

    /**
	 * Component styles.
	 *
	 * @return 	string
	 */
	public static function styles(): string {
        return <<<CSS
            .has-floating {
                text-decoration: 1px underline dotted;
                cursor: help;
            }
            .has-floating:focus {
                outline: 1px dotted;
            }
            .has-floating[data-plugin=popover],
            .has-floating[data-wp-context*=popover] {
                cursor: pointer;
            }
            .wp-floating {
                --wp--floating--zindex: 80;
                --wp--floating--max-width: 500px;
                --wp--floating--padding-x: 0.5rem;
                --wp--floating--padding-y: 0.25rem;
                --wp--floating--margin: initial;
                --wp--floating--font-size: var(--wp--preset--font-size--small);
                --wp--floating--color: var(--wp--preset--color--dark);
                --wp--floating--border-radius: 3px;
                --wp--floating--bg: var(--wp--preset--color--while);
                --wp--floating--opacity: 1;
                z-index: var(--wp--floating--zindex);
                display: block;
                margin: var(--wp--floating--margin);
                font-family: var(--wp--preset--font-family--base);
                font-size: var(--wp--floating--font-size);
                font-style: normal;
                font-weight: 400;
                text-align: left;
                text-align: start;
                text-decoration: none;
                text-shadow: none;
                text-transform: none;
                letter-spacing: normal;
                line-height: 1.5;
                line-break: auto;
                word-break: normal;
                white-space: normal;
                word-spacing: normal;
                word-wrap: break-word;
                opacity: 0;
            }
            .wp-floating.show {
                opacity: var(--wp--floating--opacity);
            }
            :is(.wp-floating__head,.wp-floating__body):empty {
                display: none;
            }
            .wp-floating__body {
                max-width: var(--wp--floating--max-width);
                padding: var(--wp--floating--padding-y) var(--wp--floating--padding-x);
                color: var(--wp--floating--color);
                text-align: var(--wp--floating--text-align, start);
                background-color: var(--wp--floating--bg);
                border-radius: var(--wp--floating--border-radius);
            }
            .wp-floating__arrow {
                position: absolute;
                display: block;
                width: var(--wp--floating--arrow-width);
                height: var(--wp--floating--arrow-height);
            }
        CSS;
	}
}