<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Styles\Components
 * @copyright   Copyright (c) 2024, WeCodeArt Framework
 * @since		6.3.7
 * @version		6.3.7
 */

namespace WeCodeArt\Support\Modules\Formatting\Styles\Floating;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Support\Styles\Components\Base;

/**
 * Module Styles
 */
class Popover extends Base {
    /**
     * Component's Style Deps.
     *
     * @var     array
     */
    static $deps = [ 'floating' ];

    /**
	 * Component styles.
	 *
	 * @return 	string
	 */
	public static function styles(): string {
        return <<<CSS
            .wp-floating--popover {
                --wp--floating--zindex: 70;
                --wp--floating--max-width: 275px;
                --wp--floating--padding-x: 1rem;
                --wp--floating--padding-y: 1rem;
                --wp--floating--color: var(--wp--preset--color--dark);
                --wp--floating--border-radius: 5px;
                --wp--floating--bg: var(--wp--preset--color--white);
                --wp--floating--opacity: 1;
                --wp--floating--text-align: left;
                --wp--floating--arrow-width: 1rem;
                --wp--floating--arrow-height: 0.5rem;
                /* Popover Only */
                --wp--floating--header-padding-x: 1rem;
                --wp--floating--header-padding-y: 0.5rem;
                --wp--floating--header-font-size: 1rem;
                --wp--floating--header-font-weight: 500;
                --wp--floating--header-color: inherit;
                --wp--floating--header-bg: var(--wp--preset--color--accent);
                --wp--floating--border-width: 1px;
                --wp--floating--border-color: var(--wp--preset--color--accent);
                --wp--floating--arrow-border: var(--wp--floating--border-color);
                --wp--floating--box-shadow: 0 0 5px rgba(0,0,0,.1);
                background-color: var(--wp--floating--bg);
                background-clip: padding-box;
                border: var(--wp--floating--border-width) solid var(--wp--floating--border-color);
                border-radius: var(--wp--floating--border-radius);
                box-shadow: var(--wp--floating--box-shadow);
            }
            .wp-floating--popover .wp-floating__head {
                padding: var(--wp--floating--header-padding-y) var(--wp--floating--header-padding-x);
                margin: 0;
                font-size: var(--wp--floating--header-font-size);
                font-weight: var(--wp--floating--header-font-weight);
                color: var(--wp--floating--header-color);
                background-color: var(--wp--floating--header-bg);
                border-bottom: var(--wp--floating--border-width) solid var(--wp--floating--border-color);
                border-top-left-radius: calc(var(--wp--floating--border-radius) - var(--wp--floating--border-width));
                border-top-right-radius: calc(var(--wp--floating--border-radius) - var(--wp--floating--border-width));
            }
            .wp-floating--popover .wp-floating__head:last-child {
                border-bottom-width: 0;
                border-bottom-left-radius: calc(var(--wp--floating--border-radius) - var(--wp--floating--border-width));
                border-bottom-right-radius: calc(var(--wp--floating--border-radius) - var(--wp--floating--border-width));
            }
            .wp-floating--popover .wp-floating__arrow::before,
            .wp-floating--popover .wp-floating__arrow::after {
                content: '';
                position: absolute;
                display: block;
                border-color: transparent;
                border-style: solid;
                border-width: 0;
            }
            
            /* Top */
            .wp-floating--popover.wp-floating--auto[data-placement^=top] > .wp-floating__arrow {
                bottom: calc(-1 * (var(--wp--floating--arrow-height)) - var(--wp--floating--border-width));
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=top] > .wp-floating__arrow::before,
            .wp-floating--popover.wp-floating--auto[data-placement^=top] > .wp-floating__arrow::after {
                border-width: var(--wp--floating--arrow-height) calc(var(--wp--floating--arrow-width) * .5) 0;
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=top] > .wp-floating__arrow::before {
                top: calc(-1 * var(--wp--floating--border-width));
                border-top-color: var(--wp--floating--arrow-border);
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=top] > .wp-floating__arrow::after {
                bottom: calc(2 * var(--wp--floating--border-width));
                border-top-color: var(--wp--floating--bg);
            }
            
            /* Right */
            /* rtl:begin:ignore */
            .wp-floating--popover.wp-floating--popover.wp-floating--auto[data-placement^=right] > .wp-floating__arrow {
                left: calc(-1 * (var(--wp--floating--arrow-height)) - var(--wp--floating--border-width));
                width: var(--wp--floating--arrow-height);
                height: var(--wp--floating--arrow-width);
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=right] > .wp-floating__arrow::before,
            .wp-floating--popover.wp-floating--auto[data-placement^=right] > .wp-floating__arrow::after {
                border-width: calc(var(--wp--floating--arrow-width) * .5) var(--wp--floating--arrow-height) calc(var(--wp--floating--arrow-width) * .5) 0;
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=right] > .wp-floating__arrow::before {
                border-right-color: var(--wp--floating--arrow-border);
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=right] > .wp-floating__arrow::after {
                left: var(--wp--floating--border-width);
                border-right-color: var(--wp--floating--bg);
            }
            /* rtl:end:ignore */

            /* Bottom */
            .wp-floating--popover.wp-floating--auto[data-placement^=bottom] > .wp-floating__arrow {
                top: calc(-1 * (var(--wp--floating--arrow-height)) - var(--wp--floating--border-width));
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=bottom] > .wp-floating__arrow::before,
            .wp-floating--popover.wp-floating--auto[data-placement^=bottom] > .wp-floating__arrow::after {
                border-width: 0 calc(var(--wp--floating--arrow-width) * .5) var(--wp--floating--arrow-height);
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=bottom] > .wp-floating__arrow::before {
                top: var(--wp--floating--border-width);
                border-bottom-color: var(--wp--floating--border-color);
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=bottom] > .wp-floating__arrow::after {
                top: calc(2 * var(--wp--floating--border-width));
                border-bottom-color: var(--wp--floating--bg);
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=bottom] > .wp-floating__head::before {
                content: '';
                position: absolute;
                top: calc(-1 * var(--wp--floating--arrow-height) + var(--wp--floating--border-width));
                left: 50%;
                display: block;
                width: var(--wp--floating--arrow-width);
                margin-left: calc(-.5 * var(--wp--floating--arrow-width));
                border-color: transparent;
                border-style: solid;
                border-width: 0 calc(var(--wp--floating--arrow-width) * .5) var(--wp--floating--arrow-height);
                border-bottom-color: var(--wp--floating--header-bg);
            }
            
            /* Left */
            /* rtl:begin:ignore */
            .wp-floating--popover.wp-floating--auto[data-placement^=left] > .wp-floating__arrow {
                right: calc(-1 * (var(--wp--floating--arrow-height)) - var(--wp--floating--border-width));
                width: var(--wp--floating--arrow-height);
                height: var(--wp--floating--arrow-width);
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=left] > .wp-floating__arrow::before,
            .wp-floating--popover.wp-floating--auto[data-placement^=left] > .wp-floating__arrow::after {
                border-width: calc(var(--wp--floating--arrow-width) * .5) 0 calc(var(--wp--floating--arrow-width) * .5) var(--wp--floating--arrow-height);
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=left] > .wp-floating__arrow::before {
                border-left-color: var(--wp--floating--arrow-border);
            }
            .wp-floating--popover.wp-floating--auto[data-placement^=left] > .wp-floating__arrow::after {
                right: var(--wp--floating--border-width);
                border-left-color: var(--wp--floating--bg);
            }
            /* rtl:end:ignore */
        CSS;
	}
}