<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Styles\Components
 * @copyright   Copyright (c) 2024, WeCodeArt Framework
 * @since		6.3.7
 * @version		6.3.7
 */

namespace WeCodeArt\Support\Modules\Formatting\Styles\Rotator;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Support\Styles\Components\Base;

/**
 * Module Styles
 */
class Zoom extends Base {
    /**
     * Component's Style Deps.
     *
     * @var     array
     */
    static $deps = [ 'rotator' ];

    /**
	 * Component styles.
	 *
	 * @return 	string
	 */
	public static function styles(): string {
        return <<<CSS
            /*---------------
             = Zoom Rotator
             = -------------*/
            .has-rotator--zoom {
                --wp--duration: .8s;
                --wp--direction: -1;
                perspective: 300px;
            }
            .has-rotator--zoom span {
                opacity: 0;
            }
            .has-rotator--zoom span:first-child:not([class]) {
                opacity: 1;
            }
            .has-rotator--zoom span.active {
                animation: __zoom-in var(--wp--duration) forwards;
            }
            .has-rotator--zoom span.inactive {
                animation: __zoom-out var(--wp--duration) forwards;
            }
             /* Letters */
            .has-rotator--zoom.letters span {
                opacity: 1;
                transform: none;
                animation: none;
            }
            .has-rotator--zoom.letters span i {
                opacity: 0;
            }
            .has-rotator--zoom.letters span:first-child:not([class]) i,
            .has-rotator--zoom.letters span.inactive i {
                opacity: 1;
                transform: translate3d(0,0,0);
            }
            .has-rotator--zoom.letters span.active i {
                animation: __zoom-in var(--wp--duration) calc(var(--wp--letter--delay) * var(--index)) forwards;
            }
            .has-rotator--zoom.letters span.inactive i {
                animation: __zoom-out var(--wp--duration) calc(var(--wp--letter--delay) * var(--index)) forwards;
            }
            @keyframes __zoom-in {
                0% {
                    opacity: 0;
                    transform: translateZ(calc(var(--wp--direction) * 100px));
                }

                100% {
                    opacity: 1;
                    transform: translate3d(0,0,0);
                }
            }

            @keyframes __zoom-out {
                0% {
                    opacity: 1;
                    transform: translate3d(0,0,0);
                }

                100% {
                    opacity: 0;
                    transform: translateZ(calc(var(--wp--direction) * 100px));
                }
            }
        CSS;
	}
}