<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Styles\Components
 * @copyright   Copyright (c) 2024, WeCodeArt Framework
 * @since		6.3.7
 * @version		6.3.7
 */

namespace WeCodeArt\Support\Modules\Formatting\Styles;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Support\Styles\Components\Base;

/**
 * Module Styles
 */
class Rotator extends Base {
    /**
     * Component's Style Deps.
     *
     * @var     array
     */
    static $deps = [];

    /**
	 * Component styles.
	 *
	 * @return 	string
	 */
	public static function styles(): string {
        return <<<CSS
            /*---------------
             = Base Rotator
             = -------------*/
            .has-rotator {
                --wp--duration: 1s;
                --wp--letter--duration: .5s;
                --wp--letter--delay: 100ms;
                position: relative;
                display: inline-flex;
                will-change: width;
                transition: width var(--wp--duration) ease-in-out;
                overflow: hidden;
            }
            .has-rotator.changed {
                overflow: clip;
            }
            .has-rotator.changing {
                overflow: visible;
            }
            .has-rotator.letters span {
                transition-duration: calc(var(--wp--letter--delay) * var(--wp--letters) + var(--wp--letter--duration));
            }
            .has-rotator span {
                display: inline-block;
                position: absolute;
                white-space: nowrap;
                perspective: inherit;
                left: 0;
                top: 0;
                transition-duration: var(--wp--duration);
            }
            .has-rotator span:first-of-type {
                position: relative;
                opacity: 1;
            }
            .has-rotator i {
                display: inline-block;
                font-weight: inherit;
                font-style: normal;
                transition-duration: var(--wp--letter--duration);
            }
        CSS;
	}
}