<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Styles\Components
 * @copyright   Copyright (c) 2024, WeCodeArt Framework
 * @since		6.3.7
 * @version		6.3.7
 */

namespace WeCodeArt\Support\Modules\Formatting\Styles\Rotator;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Support\Styles\Components\Base;

/**
 * Module Styles
 */
class Rotate extends Base {
    /**
     * Component's Style Deps.
     *
     * @var     array
     */
    static $deps = [ 'rotator' ];

    /**
	 * Component styles.
	 *
	 * @return 	string
	 */
	public static function styles(): string {
        return <<<CSS
            /*---------------
             = Rotate Effect
             = -------------*/
            .has-rotator--rotate {
                --wp--duration: 1s;
                --wp--letter--duration: .5s;
                --wp--rotate-x: 1;
                --wp--rotate-y: 0;
                --wp--degrees: 180deg;
                perspective: 300px; 
            }
            .has-rotator--rotate.inverse {
                --wp--degrees: -180deg;
            }
            .has-rotator--rotate.y {
                --wp--rotate-x: 0;
                --wp--rotate-y: 1;
            }
            .has-rotator--rotate.from-top :is(span,i) {
                transform-origin: 50% 0%;
            }
            .has-rotator--rotate.from-left :is(span,i) {
                transform-origin: 0% 50%;
            }
            .has-rotator--rotate.from-right :is(span,i) {
                transform-origin: 100% 50%;
            }
            .has-rotator--rotate.from-bottom :is(span,i) {
                transform-origin: 50% 100%;
            }
            .has-rotator--rotate span {
                transform: rotate3d(var(--wp--rotate-x),var(--wp--rotate-y),0,var(--wp--degrees));
                transform-origin: 50% 50%;
                transform-style: preserve-3d;
                backface-visibility: hidden;
            }
            .has-rotator--rotate span:first-child:not([class]) {
                transform: rotate3d(var(--wp--rotate-x),var(--wp--rotate-y),0,0);
            }
            .has-rotator--rotate span.active {
                animation: __rotate-in var(--wp--duration) forwards;
            }
            .has-rotator--rotate span.inactive {
                animation: __rotate-out var(--wp--duration) forwards;
            }
            /* Letters */
            .has-rotator--rotate.letters span {
                transform: none;
                animation: none;
            }
            .has-rotator--rotate.letters :where(i) {
                transform: rotate3d(var(--wp--rotate-x),var(--wp--rotate-y),0,var(--wp--degrees));
                transform-style: preserve-3d;
                transform-origin: 50% 50%;
                backface-visibility: hidden;
            }
            .has-rotator--rotate.letters span:first-child:not([class]) i,
            .has-rotator--rotate.letters span.inactive i {
                transform: rotate3d(var(--wp--rotate-x),var(--wp--rotate-y),0,0);
            }
            .has-rotator--rotate.letters span.active i {
                animation: __rotate-in var(--wp--letter--duration) calc(var(--wp--letter--delay) * var(--index)) forwards;
            }
            .has-rotator--rotate.letters span.inactive i {
                animation: __rotate-out var(--wp--letter--duration) calc(var(--wp--letter--delay) * var(--index)) forwards;
            }
            @keyframes __rotate-in {
                0% {
                    transform: rotate3d(var(--wp--rotate-x),var(--wp--rotate-y),0,var(--wp--degrees));
                }
                100% {
                    transform: rotate3d(0,0,0,0);
                }
            }
            @keyframes __rotate-out {
                0% {
                    transform: rotate3d(0,0,0,0);
                }
                100% {
                    transform: rotate3d(var(--wp--rotate-x),var(--wp--rotate-y),0,calc(-1 * var(--wp--degrees)));
                }
            }
        CSS;
	}
}