<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Styles\Components
 * @copyright   Copyright (c) 2024, WeCodeArt Framework
 * @since		6.3.7
 * @version		6.3.7
 */

namespace WeCodeArt\Support\Modules\Formatting\Styles\Rotator;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Support\Styles\Components\Base;

/**
 * Module Styles
 */
class Scale extends Base {
    /**
     * Component's Style Deps.
     *
     * @var     array
     */
    static $deps = [ 'rotator' ];

    /**
	 * Component styles.
	 *
	 * @return 	string
	 */
	public static function styles(): string {
        return <<<CSS
            /*---------------
             = Scale Rotator
             = -------------*/
            .has-rotator--scale {
                --wp--duration: 1s;
                --wp--letter--duration: .6s;
            }
            .has-rotator--scale span {
                opacity: 0;
                transform: scale(0);
            }
            .has-rotator--scale span:first-child:not([class]) {
                opacity: 1;
                transform: scale(1);
            }
            .has-rotator--scale span.active {
                animation: __scale-in var(--wp--duration) forwards;
            }
            .has-rotator--scale span.inactive {
                animation: __scale-out var(--wp--duration) forwards;
            }
            /* Letters */
            .has-rotator--scale.letters span {
                opacity: 1;
                transform: none;
                animation: none;
            }
            .has-rotator--scale.letters i {
                opacity: 0;
                transform: scale(0);
            }
            .has-rotator--scale.letters span:first-child:not([class]) i,
            .has-rotator--scale.letters span.inactive i {
                opacity: 1;
                transform: scale(1);
            }
            .has-rotator--scale.letters span.active i {
                animation: __scale-in var(--wp--letter--duration) calc(var(--wp--letter--delay) * var(--index)) forwards;
            }
            .has-rotator--scale.letters span.inactive i {
                animation: __scale-out var(--wp--letter--duration) calc(var(--wp--letter--delay) * var(--index)) forwards;
            }
            @keyframes __scale-in {
                0% {
                    opacity: 0;
                    transform: scale(0);
                }

                60% {
                    opacity: 1;
                    transform: scale(1.2);
                }

                100% {
                    opacity: 1;
                    transform: scale(1);
                }
            }

            @keyframes __scale-out {
                0% {
                    opacity: 1;
                    transform: scale(1);
                }

                100% {
                    opacity: 0;
                    transform: scale(0);
                }
            }
        CSS;
	}
}