<?php
/**
 * WeCodeArt Framework
 *
 * WARNING: This file is part of the core WeCodeArt Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package		WeCodeArt Framework
 * @subpackage  Styles\Components
 * @copyright   Copyright (c) 2024, WeCodeArt Framework
 * @since		6.3.7
 * @version		6.3.7
 */

namespace WeCodeArt\Support\Modules\Formatting\Styles\Rotator;

defined( 'ABSPATH' ) || exit();

use WeCodeArt\Support\Styles\Components\Base;

/**
 * Module Styles
 */
class Slide extends Base {
    /**
     * Component's Style Deps.
     *
     * @var     array
     */
    static $deps = [ 'rotator' ];

    /**
	 * Component styles.
	 *
	 * @return 	string
	 */
	public static function styles(): string {
        return <<<CSS
            /*---------------
             = Slide Rotator
             = -------------*/
            .has-rotator--slide {
                --wp--duration: 1s;
                --wp--direction: -1;
                --wp--letter--duration: 1s;
            }
            .has-rotator--slide.down {
                --wp--direction: 1;
            }
            .has-rotator--slide span {
                opacity: 0;
            }
            .has-rotator--slide span:first-child:not([class]) {
                opacity: 1; 
            }
            .has-rotator--slide span.active {
                animation: __slide-in var(--wp--duration) forwards;
            }
            .has-rotator--slide span.inactive {
                animation: __slide-out var(--wp--duration) forwards;
            }
            /* Letters */
            .has-rotator--slide.letters span {
                opacity: 1;
                transform: none;
                animation: none;
            }
            .has-rotator--slide.letters i {
                opacity: 0;
            }
            .has-rotator--slide.letters span:first-child:not([class]) i,
            .has-rotator--slide.letters span.inactive i {
                opacity: 1; 
            }
            .has-rotator--slide.letters span.active i {
                animation: __slide-in var(--wp--letter--duration) calc(var(--wp--letter--delay) * var(--index)) forwards;
            }
            .has-rotator--slide.letters span.inactive i {
                animation: __slide-out var(--wp--letter--duration) calc(var(--wp--letter--delay) * var(--index)) forwards;
            }
            @keyframes __slide-in {
                0% {
                    opacity: 0;
                    transform: translate3d(0,calc(var(--wp--direction,1) * -100%),0);
                }

                65% {
                    opacity: 1;
                    transform: translate3d(0,calc(var(--wp--direction,1) * 20%),0);
                }

                100% {
                    opacity: 1;
                    transform: translate3d(0,0,0);
                }
            }

            @keyframes __slide-out {
                0% {
                    opacity: 1;
                    transform: translate3d(0,0,0);
                }

                65% {
                    opacity: 0;
                    transform: translate3d(0,calc(var(--wp--direction) * 120%),0);
                }

                100% {
                    opacity: 0;
                    transform: translate3d(0,calc(var(--wp--direction) * 100%),0);
                }
            }
        CSS;
	}
}